name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)/AppiumEwano:$(pwd)/AppiumEwano/Pages" >> $GITHUB_ENV
     
    - name: Verify PYTHONPATH
      run: |
        echo $PYTHONPATH

    - name: Verify PYTHONPATH
      run: |
        echo $PYTHONPATH

    - name: List files in tests directory
      run: |
        ls AppiumEwano/tests
        
    - name: Start Android Emulator
      run: |
        echo "Starting Android Emulator"
        $ANDROID_HOME/emulator/emulator -avd Pixel_7_API_VanillaIceCream -no-snapshot-load -no-window &
      env:
        ANDROID_HOME: ${{ secrets.ANDROID_HOME }}

    - name: Wait for Emulator to start
      run: |
        adb wait-for-device
        adb shell input keyevent 82


    - name: Run tests
      shell: pwsh
      run: |
        $env:PYTHONPATH = "$(pwd)/AppiumEwano;$(pwd)/AppiumEwano/pages"
        echo "PYTHONPATH is set to: $env:PYTHONPATH"
        python AppiumEwano/tests/test_BalancePurchase.py
