name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)/AppiumEwano:$(pwd)/AppiumEwano/Pages" >> $GITHUB_ENV
     
    - name: Verify PYTHONPATH
      run: |
        echo $PYTHONPATH

    - name: Verify PYTHONPATH
      run: |
        echo $PYTHONPATH

    - name: List files in tests directory
      run: |
        ls AppiumEwano/tests

    - name: Run tests
      env:
        PYTHONPATH: ${{ env.PYTHONPATH }}
      run: |
        python AppiumEwano/tests/test_BalancePurchase.py
